### PR TITLE
[Merged by Bors] - docs: README.md + postgres CHANGELOG.md

### PR DESCRIPTION
**Pull request by pinkforest**
- Initial versions before new release process
- Postgres CHANGELOG.md

### CODE REVIEW

**Review by simlay — APPROVED** [review]
Thanks for this! I need to get better at doing this.

**Comment by ajhunyady** [comment]
It looks like there is a typo on the Readme.md file:

```
<div align="center">
<h1>Fluvio - Connectors</h1>
<a href="https://fluvio.io" target="_blank">
 <strong>The programmable data streaming platform - Connectors</strong>
 </a>
<br>
<br>

<div>
```

The last `<div>` should have been `</div>`. Center justified tables in this context, makes the file hard to read.

**Comment by pinkforest** [comment]
I'll do another PR

**Pull request closed without merging**
