### PR TITLE
[Merged by Bors] - Update fluvio to use consumer metrics

### PR DESCRIPTION
**Pull request by nacardin**

### CODE REVIEW

**Comment by simlay** [comment]
Is this missing some files? I only see `Cargo.lock`

**Comment by morenol** [comment]
I think that it just updates fluvio client

**Review by simlay — APPROVED** [review]
bors r+

**Comment by nacardin** [comment]
This will kick off new docker images to be published?

**Comment by sehz** [comment]
Yes, assuming use latest version tag.

**Comment by nacardin** [comment]
bors retry

**Comment by simlay** [comment]
bors retry

**Pull request closed without merging**
